version: '3.8'

services:
  backend:
    build:
      context: ./PPDiscover
      dockerfile: Dockerfile
    ports:
      - "9070:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - ppdiscover-network

  frontend:
    build:
      context: ./PPDiscover-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ppdiscover-network

networks:
  ppdiscover-network:
    driver: bridge 