version: '3.8'

services:
  frontend:
    build:
      context: ./PastoralSearch-frontend
      dockerfile: Dockerfile
    container_name: pastoral-search-frontend
    restart: unless-stopped
    networks:
      - pastoral-network

  backend:
    build:
      context: ./PastoralSearch-backend
      dockerfile: Dockerfile
    container_name: pastoral-search-backend
    restart: unless-stopped
    networks:
      - pastoral-network

  nginx:
    image: nginx:stable-alpine
    container_name: pastoral-search-nginx
    ports:
      - "9002:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - pastoral-network

networks:
  pastoral-network:
    driver: bridge 