version: '3.8'

services:
  backend:
    build:
      context: ./PastoralSearch-backend
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - pastoralsearch-network

  frontend:
    build:
      context: ./PastoralSearch-frontend
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    depends_on:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - pastoralsearch-network

networks:
  pastoralsearch-network:
    driver: bridge 