version: '3.8'

services:
  backend:
    build:
      context: ./PastoralSearch-backend
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - pastoralsearch-network

  frontend:
    build:
      context: ./PastoralSearch-frontend
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    depends_on:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - pastoralsearch-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "9002:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

networks:
  pastoralsearch-network:
    driver: bridge 