version: '3.8'

services:
  backend:
    build:
      context: ./PastoralSearch-backend
      dockerfile: Dockerfile
    expose:
      - "9001"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - pastoralsearch-network

  frontend:
    build:
      context: ./PastoralSearch-frontend
      dockerfile: Dockerfile
    expose:
      - "80"
    depends_on:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - pastoralsearch-network

  nginx:
    image: nginx:latest
    ports:
      - "9000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - pastoralsearch-network

networks:
  pastoralsearch-network:
    driver: bridge 